<?php

use Illuminate\Database\Seeder;
use App\Kelurahan;

class KelurahanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Kedaton";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Surabaya";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Sukamenanti";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Sidodadi";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Sukamenanti Baru";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Penengahan";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Penengahan Raya";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Sukarame";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Way Dadi";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Sukarame Baru";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Way Dadi Baru";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Korpri jaya";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Korpri Raya";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Gedong Air";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Sukajawa";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Susunan Baru";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Sukadana Ham";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Kelapa Tiga Permai";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Sukajawa Baru";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Segalamider";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Panjang Selatan";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Srengsem";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Panjang Utara";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Pidada";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Karang Maritim";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Way Lunik";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Ketapang";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Ketapang Kuala";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Kota Baru";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Tanjung Agung";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Kebon Jeruk";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Sawah Lama";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Sawah Brebes";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Durian Payung";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Gotong Royong";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Palapa";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Kaliawi";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Kelapa Tiga";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Pasir Gintung";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Kaliawi Persada";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Pesawahan";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Telukbetung";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Talang";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Gedong Pakuon";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Sumur Putri";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Gunungmas";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Bakung";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Kuripan";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Negeri Olok Gading";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Sukarame II";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Batu Putuk";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Kupang Kota";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Kupang Raya";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Kupang Teba";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Pengajaran";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Gulak Galik";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Sumur Batu";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Rajabasa";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Gedong Meneng";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Rajabasa Nunyai";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Rajabasa Pemuka";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Gedong Meneng Baru";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Rajabasa Raya";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Rajabasa Jaya";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Tanjung Senang";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Way Kandis";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Labuhan Dalam";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Perumnas Way Kandis";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Pematang Wangi";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Sukabumi";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Sukabumi Indah";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Campang Raya";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Nusantara Permai";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Campang Jaya";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Way Gubak";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Way Laga";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Sumber Rejo";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Beringin Jaya";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Kemiling Permai";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Sumber Agung";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Kedaung";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Pinang Jaya";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Sumberrejo Sejahtera";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Kemiling Raya";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Beringin Raya";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Labuhan Ratu";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Labuhan Ratu Raya";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Sepang Jaya";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Kota Sepang";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Kampung Baru Raya";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Kampung Baru";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Perumnas Way Halim";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Way Halim Permai";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Gunungsulah";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Jagabaya I";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Jagabaya II";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Jagabaya III";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Langkapura";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Langkapura Baru";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Gunungterang";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Bilabong Jaya";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Gunungagung";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Enggal";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Pelita";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Tanjungkarang";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Gunungsari";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Rawalaut";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Pahoman";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Kedamaian";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Bumi Kedamaian";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Tanjungagung Raya";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Tanjungbaru";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Kalibalau Kencana";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Tanjungraya";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Tanjunggading";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Kota Karang";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Kota Karang Raya";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Parwata";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Keteguhan";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Sukamaju";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Way Tataan";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Sukaraja";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Bumi Waras";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Garuntang";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Bumi Raya";
    $kelurahan->save();
$kelurahan = new Kelurahan();
    $kelurahan->nama = "Kangkung";
    $kelurahan->save();
    
    }
}
